## Práctica 4 - GitLab CI/CD (estructura final / guía)
##
## Este fichero NO contiene la solución “copiable”.
## Contiene la estructura final que deberías alcanzar tras completar los ejercicios,
## con comentarios indicando qué debes implementar en cada punto.
##
## Tu pipeline real debe ser: .gitlab-ci.yml

stages:
  - ci
  - cd

variables:
  # TODO (E2): Variables globales:
  # IMAGE_NAME: "scalian_training-java-hello-world:0.0.2"
  # APP_URL: "http://localhost:8084/hello"

ci:lint:
  stage: ci
  # TODO (E3): Ejecutar CI en contenedor:
  # image: maven:3.8.6-openjdk-11-slim
  script:
    - echo "TODO: make lint"

ci:test:
  stage: ci
  # TODO (E3): Ejecutar CI en contenedor:
  # image: maven:3.8.6-openjdk-11-slim
  script:
    - echo "TODO: make test"

ci:build-image:
  stage: ci
  image: docker:27
  services:
    # TODO (E4): Docker-in-Docker si el runner lo necesita
    - docker:27-dind
  script:
    - echo "TODO: docker build -t $IMAGE_NAME --build-arg VERSION=... -f devops/Dockerfile ."

cd:deploy:
  stage: cd
  image: docker:27
  services:
    - docker:27-dind
  rules:
    # TODO (E5): Ejecutar solo en develop/master
    - if: '$CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "master"'
      when: on_success
    - when: never
  script:
    - echo "TODO: docker compose up -d java_app"
    - echo "TODO: curl -fsS $APP_URL"
  after_script:
    # TODO (E6): Cleanup garantizado
    - echo "TODO: docker compose down --volumes || true"
    - echo "TODO: docker rmi $IMAGE_NAME || true"

